# Generated by Django 4.0.4 on 2022-05-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doencas',
            fields=[
                ('DoencaId', models.AutoField(primary_key=True, serialize=False)),
                ('DoencaNome', models.CharField(max_length=100)),
                ('DoencaDescricao', models.CharField(max_length=500)),
                ('DoencaVacina', models.BooleanField(default=False)),
                ('DoencaLink', models.CharField(max_length=100)),
            ],
        ),
    ]
