# Generated by Django 4.0.4 on 2022-05-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doencas',
            old_name='DoencaDescricao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='doencas',
            old_name='DoencaId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='doencas',
            old_name='DoencaLink',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='doencas',
            old_name='DoencaNome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='doencas',
            old_name='DoencaVacina',
            new_name='vacinadisp',
        ),
    ]
