# Generated by Django 4.0.4 on 2022-05-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_rename_doencadescricao_doencas_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idmunicipio', models.IntegerField()),
                ('iddoenca', models.IntegerField()),
                ('data', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacoesTotal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idmunicipio', models.IntegerField()),
                ('iddoenca', models.IntegerField()),
                ('casos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ususarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posto', models.CharField(choices=[('TEN', 'Tenente')], max_length=100)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('senha', models.CharField(max_length=10)),
                ('om', models.CharField(max_length=10)),
                ('foto', models.BinaryField()),
            ],
        ),
    ]
