# Generated by Django 4.0.4 on 2022-06-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_usuarios_nome_usuarios_nomeguerra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificacoesTotal',
        ),
        migrations.RemoveField(
            model_name='notificacoes',
            name='data',
        ),
        migrations.AddField(
            model_name='notificacoes',
            name='casos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
