# Generated by Django 4.0.4 on 2022-06-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_rename_cidade_localidades_nome_localidades_regiao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doencas',
            name='descricao',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='doencas',
            name='vacinadisp',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
