# Generated by Django 4.0.4 on 2022-06-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_alter_doencas_descricao_alter_doencas_vacinadisp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doencas',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doencas',
            name='vacinadisp',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
