# Generated by Django 4.0.4 on 2022-06-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_alter_doencas_descricao_alter_doencas_vacinadisp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doencas',
            name='descricao',
            field=models.CharField(default='Indisponivel', max_length=500),
        ),
        migrations.AlterField(
            model_name='doencas',
            name='vacinadisp',
            field=models.BooleanField(default=False),
        ),
    ]
