# Generated by Django 4.0.4 on 2022-06-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_alter_doencas_descricao_alter_doencas_vacinadisp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doencas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='notificacoes',
            name='iddoenca',
        ),
        migrations.AddField(
            model_name='notificacoes',
            name='nomedoenca',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='doencas',
            name='nome',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
