# Generated by Django 4.0.4 on 2022-06-05 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_remove_doencas_id_remove_notificacoes_iddoenca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacoes',
            name='idmunicipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.localidades'),
        ),
        migrations.AlterField(
            model_name='notificacoes',
            name='nomedoenca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.doencas'),
        ),
    ]
