# Generated by Django 4.0.4 on 2022-06-06 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_alter_notificacoes_idmunicipio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacoes',
            name='idmunicipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.localidades'),
        ),
        migrations.AlterField(
            model_name='notificacoes',
            name='nomedoenca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.doencas'),
        ),
    ]
